install.packages("terra")
install.packages("exactextractr")
install.packages("stars")
install.packages("sf")
install.packages("caret")
install.packages("dplyr")
install.packages("mapedit")
install.packages("devtools")
devtools::install_github("filipematias23/FIELDimageR.Extra", dependencies=FALSE)
